language: ruby
rvm:
- 2.4.1

before_script:
 - chmod +x ./script/cibuild 

script: ./script/cibuild

# branch whitelist.
branches:
  only:
  - master
  - gh-pages # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
