# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lenbitz.io
email: lenbitz@lenbitz.io
description: Random rant about code, electronics and drones.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://jekyll.lenbitz.io" # the base hostname & protocol for your site, e.g. http://example.com


# Social media usernames etc
username_twitter: lano78
usename_github: larsnordstrom
username_instagram: lenbitzFPV
username_youtube: lenbitzFPV
username_paypal: lano78
username_bitcoin: abc
username_patreon: lenbitzfpv

# google analytics
google_analytics: 0000

# Locales
timezone: Europe/Stockholm
encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


# These are to be excluded
exclude:
  - Gemfile
  - Gemfile.lock
  - run.bat
  - start.sh
  - vendor
  - script
  - lenbitz.io.sublime-project
  - lenbitz.io.sublime-workspace
  - circle.yml
  - travis.yml
  - .jekyll-metadata
  - .DS_Store
  - README.txt
  - .gitignore
  
atom:
  buildCommand:
    - jekyll
    - build
    - --watch
    - --incremental
  buildEnv:
    JEKYLL_ENV: development
